# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ryan Heyser
email: ryan@heyser.xyz
description: >-
  A commentary on DevOps in the workplace and homelab.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://blog.gh.heyser.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rumblpak
github_username: rheyser

# Theme settings
author: Ryan Heyser
avatar: https://avatars.githubusercontent.com/u/146683630
location: Atlanta, GA
skin: midnight

# Build settings
remote_theme: ngzhio/jekyll-theme-hamilton
# theme: just-the-docs 
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji
  - kramdown
  - kramdown-parser-gfm

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# kramdown
kramdown:
  input: GFM
  gfm_emojis: true
  header_offset: 2
  syntax_highlighter: coderay
  syntax_highlighter_opts:
    line_numbers: table
    tab_width: 2
    wrap: 120

# Jekyll SEO Tag
twitter:
  username: rumblpak
  card: summary
logo: https://avatars.githubusercontent.com/u/146683630
social:
  name: Ryan Heyser
  links: 
    - https://twitter.com/rumblpak
    - https://github.com/ryanheyser
lang: en
