# See https://mmistakes.github.io/minimal-mistakes/docs/configuration for details about the minimal-mistakes theme configuration.
# The default minimal-mistakes config is available at https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Required! See https://github.com/asciidoctor/jekyll-asciidoc?tab=readme-ov-file#configuration
asciidoc: {}

asciidoctor:
  attributes:
    icons: font
    source-highlighter: rouge

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author
author:
  avatar: https://avatars.githubusercontent.com/u/146683630
  bio: "Just another _bored_ engineer on the internet."
  github: rheyser # FIXME Add your GitHub username or remove this line.
  linkedin: rheyser # FIXME Add your Linkedin username or remove this line.
  location: Atlanta, GA
  name: Ryan Heyser
  email: ryan@heyser.xyz

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#giscus-comments
comments:
  giscus:
    category_name: "Blog"
    category_id: "DIC_kwDOKbHSxs4Cskpp"
    discussion_term: "og:title"
    reactions_enabled: "1"
    repo_id: R_kgDOKbHSxg
    theme: dark
  provider: giscus

copyright: Ryan Heyser

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#front-matter-defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      classes: wide
      comments: false
      layout: single
      related: true
      share: true
      show_date: true

description: >-
  A commentary on DevOps in the workplace and homelab.

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#code-block-copy-button
enable_copy_code_button: true

encoding: utf-8

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-footer
footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/ryanheyser # FIXME Replace with a link pointing to your GitHub profile (e.g. https://github.com/gwenneg) or remove this item.
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url: https://www.linkedin.com/in/rheyser # FIXME Replace with a link pointing to your Linkedin profile (e.g. https://www.linkedin.com/in/gwenneg) or remove this item.

locale: en-US

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin
minimal_mistakes_skin: dark

remote_theme: mmistakes/minimal-mistakes@4.27.0

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-repository
repository: "ryanheyser/blog.gh.heyser.xyz"

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-search
search: true

show_excerpts: true

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-subtitle
# subtitle: The newest blog ever. # FIXME Replace with your blog subtitle (optional).

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings
tag_archive:
  type: liquid
  path: /tags/

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-title
title: Ryan Heyser

url: "https://blog.gh.heyser.xyz"
